name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [macos-10.14, ubuntu-18.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 300000 --ignore-scripts

      - name: Bootstrap
        run: yarn lerna bootstrap

      - name: Lint (ESLint + Prettier)
        run: yarn lint-since

      - name: Test
        run: yarn test-since
